// motivational_quotes.dart

import 'dart:math';

import 'package:flutter/material.dart';

class MotivationalQuotes {
  static List<String> _quotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Life is 10% what happens to us and 90% how we react to it",
    "The future belongs to those who believe in the beauty of their dreams",
    "Happiness is not something ready-made. It comes from your own actions",
    "The only person you should try to be better than is the person you were yesterday",
    "Don't count the days; make the days count",
    "It does not matter how slowly you go as long as you do not stop",
    "The greatest glory in living lies not in never falling, but in rising every time we fall",
    "To live is the rarest thing in the world. Most people exist, that is all",
    "Success usually comes to those who are too busy to be looking for it",
    "The only limit to our realization of tomorrow will be our doubts of today",
    "It's not whether you get knocked down, it's whether you get up",
    "I can't change the direction of the wind, but I can adjust my sails to always reach my destination",
    "If you want to achieve greatness stop asking for permission",
    "The secret of getting ahead is getting started",
    "You miss 100% of the shots you don't take",
    "The best revenge is massive success",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it",
    "You are never too old to set another goal or to dream a new dream",
    "The harder I work, the luckier I get",
    "Don't watch the clock; do what it does. Keep going",
    "The only way to do great work is to love what you do",
    "In three words I can sum up everything I've learned about life: it goes on",
    "The best time to plant a tree was 20 years ago. The second best time is now",
    "Life is what happens when you're busy making other plans",
    "The only thing we have to fear is fear itself",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment",
    "The journey of a thousand miles begins with one step",
    "Believe you can and you're halfway there",
    "In the end, we will remember not the words of our enemies, but the silence of our friends",
    "Your time is limited, don't waste it living someone else's life",
    "If you don't stand for something, you will fall for anything",
    "The only true wisdom is in knowing you know nothing",
    "The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks",
    "Life is really simple, but we insist on making it complicated",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it",
    "The only limit to our realization of tomorrow will be our doubts of today",
    "The road to success and the road to failure are almost exactly the same",
    "Do not wait to strike till the iron is hot; but make it hot by striking",
    "I can't change the direction of the wind, but I can adjust my sails to always reach my destination",
    "You are never too old to set another goal or to dream a new dream",
    "The only thing necessary for the triumph of evil is for good men to do nothing",
    "Success is walking from failure to failure with no loss of enthusiasm",
    "In the middle of every difficulty lies opportunity",
    "The only thing you can control is your attitude toward the situation",
    "The only person you should try to be better than is the person you were yesterday",
    "It's not the years in your life that count. It's the life in your years",
    "The best way to predict the future is to create it",
    "Dream big and dare to fail",
    "Don't let yesterday take up too much of today",
    "I find that the harder I work, the more luck I seem to have",
    "The more you praise and celebrate your life, the more there is in life to celebrate",
    "Life is change, growth is optional. Choose wisely",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle",
    "The secret of getting ahead is getting started",
    "It is never too late to be what you might have been",
    "Life is either a daring adventure or nothing at all",
    "In the end, we will remember not the words of our enemies, but the silence of our friends",
    "To succeed in life, you need two things: ignorance and confidence",
    "The only limit to our realization of tomorrow will be our doubts of today",
    "Don't watch the clock; do what it does. Keep going.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Success is not in what you have, but who you are.",
    "The only way to do great work is to love what you do.",
    "It's not about how bad you want it. It's about how hard you're willing to work for it.",
    "Doubt kills more dreams than failure ever will.",
    "In the middle of every difficulty lies opportunity.",
    "You are the master of your destiny. You can influence, direct, and control your own environment. You can make your life what you want it to be.",
    "Your time is limited, so don't waste it living someone else's life.",
    "If you want to achieve greatness, stop asking for permission.",
    "Do what you can, with what you have, where you are.",
    "The best revenge is massive success.",
    "Opportunities don't happen. You create them.",
    "The secret of getting ahead is getting started.",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
    "Great minds discuss ideas; average minds discuss events; small minds discuss people.",
    "You miss 100% of the shots you don't take.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The journey of a thousand miles begins with one step.",
    "Failure is the condiment that gives success its flavor.",
    "Life is short, and it is up to you to make it sweet.",
    "The secret of getting ahead is getting started.",
    "In order to be irreplaceable, one must always be different.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "It is not the mountain we conquer, but ourselves.",
    "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "You are the sum total of everything you've ever seen, heard, eaten, smelled, been told, forgot - it's all there. Everything influences each of us, and because of that, I try to make sure that my experiences are positive.",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
    "The best way to predict the future is to create it.",
    "Success usually comes to those who are too busy to be looking for it.",
    "It is our choices that show what we truly are, far more than our abilities.",
    "Don't let yesterday take up too much of today.",
    "In the midst of chaos, there is also opportunity.",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.",
    "Our greatest glory is not in never falling, but in rising every time we fall.",
    "The only thing necessary for the triumph of evil is for good men to do nothing.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "The secret to success is to know something nobody else knows.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks.",
    "Life is really simple, but we insist on making it complicated.",
    "The only way to do great work is to love what you do.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "The only person you should try to be better than is the person you were yesterday.",
    "The only thing you can control is your attitude toward the situation.",
    "The only true wisdom is in knowing you know nothing.",
    "The only thing necessary for the triumph of evil is for good men to do nothing.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Life is what happens when you're busy making other plans.",
    "The only thing we have to fear is fear itself.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "The journey of a thousand miles begins with one step.",
    "Believe you can and you're halfway there.",
    "In the end, we will remember not the words of our enemies, but the silence of our friends.",
    "Your time is limited, don't waste it living someone else's life.",
    "Success is not in what you have, but who you are.",
    "It's not about how bad you want it. It's about how hard you're willing to work for it.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Don't watch the clock; do what it does. Keep going.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Doubt kills more dreams than failure ever will.",
    "You are the master of your destiny. You can influence, direct, and control your own environment. You can make your life what you want it to be.",
    "If you want to achieve greatness, stop asking for permission.",
    "Do what you can, with what you have, where you are.",
    "The best revenge is massive success.",
    "Opportunities don't happen. You create them.",
    "The secret of getting ahead is getting started.",
    "Life is short, and it is up to you to make it sweet.",
    "The secret of getting ahead is getting started.",
    "In order to be irreplaceable, one must always be different.",
    "Success is not how high you have climbed, but how you make a positive difference to the world.",
    "It is not the mountain we conquer, but ourselves.",
    "The only thing that stands between you and your dream is the will to try and the belief that it is actually possible.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
    "You are the sum total of everything you've ever seen, heard, eaten, smelled, been told, forgot - it's all there. Everything influences each of us, and because of that, I try to make sure that my experiences are positive.",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.",
    "The best way to predict the future is to create it.",
    "Success usually comes to those who are too busy to be looking for it.",
    "It is our choices that show what we truly are, far more than our abilities.",
    "Don't let yesterday take up too much of today.",
    "In the midst of chaos, there is also opportunity.",
    "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.",
    "Our greatest glory is not in never falling, but in rising every time we fall.",
    "The only thing necessary for the triumph of evil is for good men to do nothing.",
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",
    "The secret to success is to know something nobody else knows.",
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",
    "The biggest risk is not taking any risk. In a world that is changing quickly, the only strategy that is guaranteed to fail is not taking risks.",
    "Life is really simple, but we insist on making it complicated.",
    "The only way to do great work is to love what you do.",
    "In three words I can sum up everything I've learned about life: it goes on.",
    "The only person you should try to be better than is the person you were yesterday.",
    "The only thing you can control is your attitude toward the situation.",
    "The only true wisdom is in knowing you know nothing.",
    "The only thing necessary for the triumph of evil is for good men to do nothing.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Life is what happens when you're busy making other plans.",
    "The only thing we have to fear is fear itself.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "The journey of a thousand miles begins with one step.",
    "Believe you can and you're halfway there.",
    "In the end, we will remember not the words of our enemies, but the silence of our friends.",
    "Your time is limited, don't waste it living someone else's life.",
    "Success is not in what you have, but who you are.",
    "It's not about how bad you want it. It's about how hard you're willing to work for it.",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "Don't watch the clock; do what it does. Keep going.",
    "The harder you work for something, the greater you'll feel when you achieve it.",
    "Doubt kills more dreams than failure ever will.",
    "You are the master of your destiny. You can influence, direct, and control your own environment. You can make your life what you want it to be.",
    "If you want to achieve greatness, stop asking for permission.",
    "Do what you can, with what you have, where you are.",
    "The best revenge is massive success.",
    "Opportunities don't happen. You create them.",
    "The secret of getting ahead is getting started.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "The best time to plant a tree was 20 years ago. The second best time is now.",
    "Life is what happens when you're busy making other plans.",
    "The only thing we have to fear is fear itself.",
    "To be yourself in a world that is constantly trying to make you something else is the greatest accomplishment.",
    "The journey of a thousand miles begins with one step.",
    "Believe you can and you're halfway there.",
    "In the end, we will remember not the words of our enemies, but the silence of our friends.",
    "Your time is limited, don't waste it living someone else's life.",
    "Success is not in what you have, but who you are.",
    "It's not about how bad you want it. It's about how hard you're willing to work for it.",
    "The only limit to our realization of tomorrow will be our doubts of today.",

    // Add more quotes here
  ];

  MotivationalQuotes() {}

  static String getRandomQuote() {
    final random = Random();
    final index = random.nextInt(_quotes.length);
    return _quotes[index];
  }
}
